import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  botaoAdicionar: {
    backgroundColor: '#28a745',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    width: '30%',
    height: '40%',
  },
  botaoRemover: {
    backgroundColor: '#dc3545',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    width: '30%',
    height: '40%',
  },
  botaoResetar: {
    backgroundColor: '#007bff',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    width: '30%',
    height: '40%',
  },
  buttonTxt: {
    color: 'white',
    fontSize: 40,
    fontFamily: 'Arial',
  },
  resetTxt: {
    color: 'white',
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Tahoma',
    alignSelf: 'center',
  },
  text: {
    fontSize: 26,
    fontFamily: 'Georgia',
    color: 'grey',
    textShadowColor: '#aaa',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    alignSelf: 'center',
  },
  text2: {
    fontSize: 60,
    fontFamily: 'Courier New',
    fontWeight: 'bold',
    color: 'black',
    alignSelf: 'center',
    textShadowColor: '#aaa',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
  },
  view: {
    flex: 0.4,
    borderWidth: 3,
    borderColor: 'Red',
    marginTop: 50,
    alignItems: 'center',
    width: '77%',
    alignSelf: 'center',
  },
  bottomContainer: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  topContainer: {
    flex: 2,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
});

export { styles };
